### ISSUE TITLE
Don't indent when there is unselected non-whitespace on selection lines

### ISSUE THREAD

**Issue by varkor** [usernamehw/vscode-indent-one-space#2]
Consider the following selection:
![image](https://user-images.githubusercontent.com/3943692/35824422-b9af6baa-0aaa-11e8-86e0-8db92f749513.png)
Here, I want to replace the newline with a single space, but the extension instead indents both lines. When the start of the selection is _after_ non-whitespace characters (on the line of the selection start), it would be better not to intercept the space input.

If I want to indent a line, I'll usually have selected from the start of the line:
![image](https://user-images.githubusercontent.com/3943692/35824551-19c5a8b0-0aab-11e8-9e24-ea44f4f05a21.png)

Even if there were an option for this behaviour, that would fix the small niggle I have with this extension!

**Comment by varkor** [comment]
Actually, maybe even more specifically: replace selection with a space when there is any non-whitespace text on either the first or last lines of the selection. I also often want to replace a word with a space. Again, if I want to indent, I'll select all the text. I suspect I'm not the only one with this use case, so an option would be super useful!

**Comment by usernamehw** [comment]
@varkor For the first item there is a special command: `editor.action.joinLines` [tips-and-tricks: join line](https://github.com/Microsoft/vscode-tips-and-tricks#join-line)

Not sure I understand the 2nd though. `|` - selection boundaries, `●` - space:
```javascript
// no-op
● |while(1) {
     'void te|xt'; ●
// no-op
● w|hile(1) {
     'void te|xt'; ●
// no-op
● w|hile(1) {
     'void text';| ●
// no-op
● w|hil|e ●
// no-op
● w|hile| ●
// no-op
● |whil|e ●

// op
● |while| ●
// op
● |while(1) {
     'void text';| ●
```

**Comment by varkor** [comment]
Yes, those examples reflect what I meant: e.g.
![image](https://user-images.githubusercontent.com/3943692/35828181-8086d1b8-0ab6-11e8-96a5-dd5918712a3e.png)
I would prefer pressing space here to add a space rather than indent.
Whereas pressing space here would indent:
![image](https://user-images.githubusercontent.com/3943692/35828269-ca9f69fe-0ab6-11e8-9cf8-e587b1f08b9f.png)

**Comment by usernamehw** [comment]
A new option should do what you wanted: `"indentOneSpace.onlyCompleteRange": true`

**Comment by varkor** [comment]
Amazing, thank you!
