### ISSUE TITLE
Allow shift-space to un-indent a line by one space

### ISSUE THREAD

**Issue by varkor** [usernamehw/vscode-indent-one-space#3]
Another (hopefully small) request. (Though there may be some way to do this that I haven't discovered.)

If at the start of a line, it would be useful to have shift-space un-indent the line by one space (like shift-tab un-indents it). Pressing backspace deletes all the spaces until the next tab stop, which is often not what's wanted.

Essentially, making shift-space have the same behaviour when no text is selected as when it there is some text selected. Shift-space doesn't seem to have any extra function at the moment, so this should be non-invasive.

**Comment by usernamehw** [comment]
`keybindings.json`
```json
{
    "key": "shift+space",
    "command": "extension.reverseIndentOneSpace",
    "when": "editorTextFocus && !editorReadonly"
},
```

**Comment by varkor** [comment]
Perfect, thank you!

**Comment by varkor** [comment]
Sorry, I got a little confused. Is there a way to force this behaviour only when there is only whitespace to the left of the caret? If I press shift+space at the end of a line, I don't want to unindent, which is what this key-binding will do.

I accidentally hit shift+space at other times, otherwise, and end up accidentally un-indenting text, which is problematic, as I can't easily re-indent one space, without jumping to the start of the line, and jumping back again.

**Comment by usernamehw** [comment]
Right now I don't have any time
