### ISSUE TITLE
which theme

### ISSUE THREAD

**Issue by MehbubRashid** [usernamehw/vscode-indent-one-space#5]
Hi, i want to say sorry because this is not actually an issue,,i would like to know the name of the 
theme that is on your demo image..thanks

**Comment by usernamehw** [comment]
Palenight: https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme

It might look different now since this gif was made some time ago.

**Comment by MehbubRashid** [comment]
Thank  you!
