### ISSUE TITLE
command 'extension.reverseIndentOneSpace' works but "shift + space" does not

### ISSUE THREAD

**Issue by singularitti** [usernamehw/vscode-indent-one-space#9]
When I type "shift + space", it just indents by one space.

I have checked my shortcut settings, and there does not appear to have any conflict:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/25192197/187386176-a9382353-3387-4bd5-9aad-9ecc24d150e2.png">

VS Code version:
```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0
```

Extension version: v0.2.8

**Comment by usernamehw** [comment]
Maybe VSCode made breaking changes to "when" clauses? 

Could you try to remove the `" && !editorReadOnly"` or replace it with `" && !editorReadonly"`?

**Comment by usernamehw** [comment]
Or maybe MacOS has something assigned to <kbd>Shift</kbd>+<kbd>Space</kbd>?

**Comment by singularitti** [comment]
Thank you for your timely reply!
I forgot I need to select a range of text to do this. This issue is a false alarm.
